# Local preview of the documentation site, with the same Jekyll and plugin versions GitHub
# Pages uses:
#
#     cd docs && bundle install && bundle exec jekyll serve
#
source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
